name: Blueprint CI/CD
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          always-auth: true
          cache-dependency-path: yarn.lock
      - name: Install dependencies and build
        run: |
          yarn
          yarn build
      - name: Setup .yarnrc.yml and publish
        if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          yarn config set npmAuthToken $NPM_AUTH_TOKEN
          yarn config set npmAlwaysAuth true
          yarn npm publish --access public

